version: '3.8'

x-common-variables: &common-variables
  MYSQL_USER: literacy
  MYSQL_PASSWORD: '***CHANGE_HERE***'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd
      - ./nginx/ssl:/etc/nginx/ssl
      - ./www:/var/www/html
    depends_on:
      - api

  api:
    image: node:lts
    volumes:
      - ./api:/api
    working_dir: "/api"
    depends_on:
      - db
    ports:
      - 3000:3000
    command: >
      bash -c "npm i &&
      npm start"
    environment:
      <<: *common-variables

  db:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      <<: *common-variables
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      TZ: "Asia/Tokyo"